config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'static_pages#index'
  resources :chat_rooms, only: [:new, :create, :show, :index]
  resources :chat_room_requests, only: :create
  resources :users, only: :show  
  
  mount ActionCable.server => '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat_room.rb
class ChatRoom < ApplicationRecord
  belongs_to :user
  has_many :messages, dependent: :destroy

  validates_uniqueness_of :room_code

  before_create :generate_room_code!

  delegate :name, to: :user, prefix: true

  private

  def generate_room_code!
    self.room_code = loop do
      random_room_code = rand.to_s[2..6]
      break random_room_code unless self.class.exists?(room_code: random_room_code)
    end
  end
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :chat_room

  validates :body, presence: true, length: {minimum: 2, maximum: 1000}

  delegate :id, to: :user, prefix: true

  after_create_commit { MessageBroadcastJob.perform_later(self) }

  def timestamp
    created_at.strftime('%H:%M:%S %d %B %Y')
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :chat_rooms, dependent: :destroy
  has_many :messages, dependent: :destroy

  validates :first_name, :last_name, presence: true

  def name
    "#{first_name} #{last_name}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/chat_room_requests_controller.rb
class ChatRoomRequestsController < ApplicationController
  before_action :authenticate_user!

  def create    
    @chat_room = ChatRoom.find_by_room_code(chat_room_request_params[:room_code])
    
    if @chat_room.nil?
      flash[:alert] = "No chat room found!"
      respond_to do |format|
        format.json { render json: {error: "No chat room found!"}, status: :unprocessable_entity }
      end      
    else
      respond_to do |format|
        format.json { render json: @chat_room.as_json(include: :messages) }
      end   
    end
  end

  private

  def chat_room_request_params
    params.require(:chat_room_requests).permit(:room_code)
  end
end

app/controllers/chat_rooms_controller.rb
class ChatRoomsController < ApplicationController
  before_action :authenticate_user!

  def index
    render component: 'Main', props: { current_user: current_user }
  end

  def show
    @chat_room = ChatRoom.includes(:messages).find_by_id(params[:id])
    @message = Message.new
  end

  def new
    @chat_room = ChatRoom.new
  end

  def create
    @chat_room = current_user.chat_rooms.build
    if @chat_room.save
      respond_to do |format|
        format.json { render json: @chat_room.as_json(include: :messages) }
      end
    else
      render 'new'
    end
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
    if current_user.present?
      redirect_to chat_rooms_path
    else
      render layout: 'landing_page'
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def display_date(datetime)
    begin
      datetime.strftime("%m/%d/%Y")
    rescue
    end
  end
  
  def display_datetime(datetime)
    begin
      datetime.strftime("%m/%d/%Y %l:%M %p")
    rescue
      # display nothing
    end
  end
end

app/helpers/chat_room_requests_helper.rb
module ChatRoomRequestsHelper
end

app/helpers/chat_rooms_helper.rb
module ChatRoomsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/chat_rooms/index.html.erb
<h1>Chat rooms</h1>

<p class="lead"><%= link_to 'New chat room', new_chat_room_path, class: 'btn btn-primary' %></p>

<%= simple_form_for :chat_room_requests, url: chat_room_requests_path, method: :post do |f| %>
  <h5>Enter 5 Digit Room Code</h5>

  <%= f.input :room_code %>
<% end %>  

app/views/chat_rooms/new.html.erb
<h1>Add chat room</h1>

<%= form_for @chat_room do |f| %>
  <%= f.submit "Create New Chat Room", class: 'btn btn-primary' %>
<% end %>

app/views/chat_rooms/show.html.erb
<ul>
  <li>Board Number: <%= @chat_room.room_code  %></li>
  <li>Created By: <%= @chat_room.user_name %></li>
  <li>Created On: <%= display_date(@chat_room.created_at) %></li>
</ul>

<div id="messages" data-chat-room-id="<%= @chat_room.id %>">
  <%= render @chat_room.messages %>
</div>

<%= form_for @message, url: '#' do |f| %>
  <div class="form-group">
    <%= f.label :body %>
    <%= f.text_area :body, class: 'form-control' %>
    <small class="text-muted">From 2 to 1000 characters</small>
  </div>

  <%= f.submit "Post", class: 'btn btn-primary btn-lg', data: { disable_with: 'Sending...' } %>
<% end %>

app/views/landing_page/_about.html.erb
<div id="about" class="section p-a-0 align-c">
  <div class="container-fluid p-x-0">
    <div class="row row-table">
      <div class="col-sm-4 block-invert p-x-30-sm-max p-x-60-md-min p-t-20-sm-min align-t-sm-min">
        <div class="col-inner p-y-50-sm-min p-y-30-xs-max max-width m-x-auto-xs-max">
          <div class="icon-box _center">
            <div class="icon-box-media">
              <img src="assets/icon/rocket.png" alt="" data-sr="bottom">
            </div>
            <div class="icon-box-heading">
              <h3>About App / Product</h3>
            </div>
            <div class="icon-box-content">
              <p>At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident.</p>
            </div>
          </div>
        </div>
      </div>

      <div class="col-sm-4 block-pink p-x-30-sm-max p-x-60-md-min p-t-20-sm-min align-t-sm-min">
        <div class="col-inner p-y-50-sm-min p-y-30-xs-max max-width m-x-auto-xs-max">
          <div class="icon-box _center">
            <div class="icon-box-media">
              <img src="assets/icon/crown.png" alt="" data-sr="bottom">
            </div>
            <div class="icon-box-heading">
              <h3>About App / Product</h3>
            </div>
            <div class="icon-box-content">
              <p>At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident.</p>
            </div>
          </div>
        </div>
      </div>

      <div class="col-sm-4 block-light p-x-30-sm-max p-x-60-md-min p-t-20-sm-min align-t-sm-min">
        <div class="col-inner p-y-50-sm-min p-y-30-xs-max max-width m-x-auto-xs-max">
          <div class="icon-box _center">
            <div class="icon-box-media">
              <img src="assets/icon/diamond.png" alt="" data-sr="bottom">
            </div>
            <div class="icon-box-heading">
              <h3>About App / Product</h3>
            </div>
            <div class="icon-box-content">
              <p>At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident.</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div> <!-- #about -->

app/views/landing_page/_brief.html.erb
<div id="brief_1" class="section block-default align-c-xs-max">
  <div class="container">
    <div class="row row-table">
      <div class="col-sm-6">
        <div class="col-inner">
          <div class="section-heading">
            <h5>Flat Style Landing Page</h5>
            <h2>App Brief Section #1</h2>
            <p>At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores.</p>
          </div> <!-- .section-heading -->
          <div class="section-content">
            <ul class="icon-list align-l m-t-30">
              <li><img src="assets/icon/chat.png" alt=""> Quisque sapien metus, ornare ac suscipit eget.</li>
              <li><img src="assets/icon/pencil.png" alt=""> Quisque sapien metus, ornare ac suscipit eget.</li>
              <li><img src="assets/icon/skull.png" alt=""> Quisque sapien metus, ornare ac suscipit eget.</li>
            </ul>
            <a class="btn btn-primary m-y-5" href="#brief_2">Learn More</a>
            <a class="btn btn-invert m-y-5" href="#brief_2">More Button</a>
          </div> <!-- .section-content -->
        </div>
      </div>
      <div class="col-sm-6 m-t-60-xs-max p-l-60-md-min">
        <div class="col-inner clearfix">
          <img class="img-responsive float-r-sm-min m-x-auto-xs-max" src="assets/item/brief-1.png" alt="" data-sr="right">
        </div>
      </div>
    </div>
  </div>
</div> <!-- #brief_1 -->

<div id="brief_2" class="section block-warning align-c-xs-max">
  <div class="container">
    <div class="row row-table">
      <div class="col-sm-6 m-b-60-xs-max p-r-60-md-min">
        <div class="col-inner clearfix">
          <img class="img-responsive float-l-sm-min m-x-auto-xs-max" src="assets/item/brief-2.png" alt="" data-sr="left">
        </div>
      </div>
      <div class="col-sm-6">
        <div class="col-inner">
          <div class="section-heading">
            <h5>Flat Style Landing Page</h5>
            <h2>App Brief Section #2</h2>
          </div> <!-- .section-heading -->
          <div class="section-content">
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam in scelerisque nisi, a convallis nibh. Etiam posuere faucibus lectus, quis volutpat urna consequat et. Aenean rutrum dui in turpis feugiat, at facilisis dui laoreet.</p>
            <p>At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores.</p>
            <a class="btn btn-success m-y-5" href="#brief_3">Learn More</a>
            <a class="btn btn-pink m-y-5" href="#brief_3">More Button</a>
          </div> <!-- .section-content -->
        </div>
      </div>
    </div>
  </div>
</div> <!-- #brief_2 -->

<div id="brief_3" class="section block-success align-c-xs-max">
  <div class="container">
    <div class="row row-table">
      <div class="col-sm-6">
        <div class="col-inner">
          <div class="section-heading">
            <h5>Flat Style Landing Page</h5>
            <h2>App Brief Section #3</h2>
            <p>At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores.</p>
          </div> <!-- .section-heading -->
          <div class="section-content">
            <ul class="icon-list align-l m-t-30">
              <li><img src="assets/icon/camera.png" alt=""> Quisque sapien metus, ornare ac suscipit eget.</li>
              <li><img src="assets/icon/support.png" alt=""> Quisque sapien metus, ornare ac suscipit eget.</li>
              <li><img src="assets/icon/paint.png" alt=""> Quisque sapien metus, ornare ac suscipit eget.</li>
            </ul>
            <a class="btn btn-primary m-y-5" href="#pricing">Our Plan</a>
            <a class="btn btn-invert m-y-5" href="#pricing">More Button</a>
          </div> <!-- .section-content -->
        </div>
      </div>
      <div class="col-sm-6 m-t-60-xs-max p-l-60-md-min">
        <div class="col-inner clearfix">
          <img class="img-responsive float-r-sm-min m-x-auto-xs-max" src="assets/item/brief-3.png" alt="" data-sr="right">
        </div>
      </div>
    </div>
  </div>
</div> <!-- #brief_3 -->

app/views/landing_page/_contact.html.erb
<div id="contact" class="section block-default">
  <div class="container">
    <div class="section-heading text-center">
      <h5>Flat Style Landing Page</h5>
      <h2>Get in touch with us</h2>
      <p>At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident.</p>
    </div>
    <div class="row section-content m-t-60-sm-min">
      <div class="col-sm-6 col-md-5">
        <div class="col-inner">
          <div class="icon-box _left">
            <div class="icon-box-media">
              <img src="assets/icon/mobile.png" alt="" data-sr="bottom">
            </div>
            <div class="icon-box-heading">
              <h4>Phone Number</h4>
            </div>
            <div class="icon-box-content font-sub font-italic">
              <span>(00) 123-4567890 (tel-1)</span>
              <br>
              <span>(00) 123-4567890 (tel-2)</span>
            </div>
          </div>

          <div class="icon-box _left">
            <div class="icon-box-media">
              <img src="assets/icon/mail.png" alt="" data-sr="bottom">
            </div>
            <div class="icon-box-heading">
              <h4>Email Address</h4>
            </div>
            <div class="icon-box-content font-sub font-italic">
              <span>email_1@example.com</span>
              <br>
              <span>email_2@example.com</span>
            </div>
          </div>

          <div class="icon-box _left">
            <div class="icon-box-media">
              <img src="assets/icon/pin.png" alt="" data-sr="bottom">
            </div>
            <div class="icon-box-heading">
              <h4>Business address</h4>
            </div>
            <div class="icon-box-content font-sub font-italic">
              <span>631 Main Street Cottage,</span>
              <br>
              <span>Long Branch, P.O Box 55016</span>
            </div>
          </div>
        </div>
      </div>
      <div class="col-sm-6 col-md-offset-1 m-t-60-xs-max">
        <div class="col-inner">
          <form class="_default" id="contactForm" novalidate="novalidate">
            <div class="form-group required">
              <label class="form-label" for="contactName">Your name</label>
              <input class="form-control" id="contactName" type="text" name="name">
            </div>
            <div class="form-group required">
              <label class="form-label" for="contactEmail">Email address</label>
              <input class="form-control" id="contactEmail" type="text" name="email">
            </div>
            <div class="form-group required">
              <label class="form-label" for="contactMessage">Message</label>
              <textarea class="form-control" id="contactMessage" rows="4" name="message"></textarea>
            </div>
            <div class="btn-wrap">
              <button type="submit" class="btn btn-primary btn-block">Send Message</button>
            </div>
            <div class="form-notify"></div>
          </form> <!-- #contactForm -->
        </div>
      </div>
    </div>
  </div>
</div> <!-- #contact -->

app/views/landing_page/_download.html.erb
<div id="download" class="section block-primary align-c">
  <div class="container">
    <div class="row">
      <div class="col-xs-12">
        <div class="col-inner">
          <div class="section-heading">
            <h5>Download Available</h5>
            <h2>Get It Right Now!</h2>
            <p>At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident.</p>
          </div>
          <div class="section-content">
            <a class="btn btn-pink m-y-5"><i class="fa fa-android"></i>Google Play</a>
            <a class="btn btn-warning m-y"><i class="fa fa-apple"></i>App Store</a>
          </div> <!-- .section-content -->
        </div>
      </div>
    </div>
  </div>
</div> <!-- #download --> 

app/views/landing_page/_pricing.html.erb
<div id="pricing" class="section block-light align-c">
  <div class="container">
    <div class="row">
      <div class="col-xs-12">
        <div class="col-inner">
          <div class="section-heading">
            <h5>Pricing Table Section</h5>
            <h2>Free And Business Plan</h2>
            <p>At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident.</p>
          </div>
          <div class="section-content m-t-60-sm-min">
            <div class="row">
              <div class="col-xs-12 col-sm-4">
                <div class="pricing-table m-t-0-xs-max">
                  <div class="pricing-table-header block-invert">
                    <h5 class="pricing-table-caption">Checkmark pricing table</h5>
                    <h2 class="pricing-table-title">FREE</h2>
                  </div>
                  <div class="pricing-table-content block-light">
                    <ul class="pricing-table-list">
                      <li><i class="fa fa-check"></i> Up to 25 users</li>
                      <li><i class="fa fa-check"></i>500 messages</li>
                      <li><i class="fa fa-check"></i>Normal options</li>
                      <li><i class="fa fa-check"></i>Phone support</li>
                    </ul>
                  </div>
                  <div class="pricing-table-footer block-light">
                    <a class="btn btn-primary" href="#download">Download</a>
                  </div>
                </div> <!-- .pricing-table -->
              </div>
              <div class="col-xs-12 col-sm-4">
                <div class="pricing-table">
                  <div class="pricing-table-header block-primary">
                    <span class="pricing-table-badge">
                      <i class="fa fa-star"></i>
                    </span>
                    <h5 class="pricing-table-caption">With badge</h5>
                    <h2 class="pricing-table-title"><span>$</span>45<span>/ mo.</span></h2>
                  </div>
                  <div class="pricing-table-content block-light">
                    <ul class="pricing-table-list">
                      <li><i class="fa fa-check"></i> Up to 150 users</li>
                      <li><i class="fa fa-check"></i> 2000 messages</li>
                      <li><i class="fa fa-check"></i> Advanced options</li>
                      <li><i class="fa fa-check"></i> Phone support</li>
                    </ul>
                  </div>
                  <div class="pricing-table-footer block-light">
                    <a class="btn btn-primary" href="#download">Download</a>
                  </div>
                </div> <!-- .pricing-table -->
              </div>
              <div class="col-xs-12 col-sm-4">
                <div class="pricing-table">
                  <div class="pricing-table-header block-pink">
                    <h5 class="pricing-table-caption">Icon pricing table</h5>
                    <h2 class="pricing-table-title"><span>$</span>75<span>/ mo.</span></h2>
                  </div>
                  <div class="pricing-table-content block-light">
                    <ul class="pricing-table-list">
                      <li><i class="fa fa-user-plus"></i> Up to 500 users</li>
                      <li><i class="fa fa-envelope"></i> <span class="color-pink">Unlimited</span> messages</li>
                      <li><i class="fa fa-cog"></i> Advanced options</li>
                      <li><i class="fa fa-support"></i> Phone support</li>
                    </ul>
                  </div>
                  <div class="pricing-table-footer block-light">
                    <a class="btn btn-primary" href="#download">Download</a>
                  </div>
                </div> <!-- .pricing-table -->
              </div>
            </div>
          </div> <!-- .section-content -->
        </div>
      </div>
    </div>
  </div>
</div> <!-- #download -->

app/views/landing_page/_top.html.erb
<div id="home" class="section block-primary position-r align-c-xs-max">
  <div id="particles-js" class="site-bg">
    <div class="site-bg-img"></div>
    <div class="site-bg-video"></div>
    <div class="site-bg-overlay"></div>
    <div class="site-bg-effect layer" data-depth=".30"></div>
    <canvas class="site-bg-canvas layer" data-depth=".30"></canvas>
  </div> <!-- .site-bg -->

  <div class="container">
    <div class="row row-table">
      <div class="col-sm-6">
        <div class="col-inner" data-sr="left">
          <div class="section-heading">
            <h5>Flat Style Landing Page</h5>
            <h1>A Flat Style Landing Page For Your App / Product</h1>
            <p>At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum</p>
          </div> <!-- .section-heading -->
          <div class="section-content">
            <a class="btn btn-pink m-y-5" href="#about">Learn More</a>
            <a class="btn btn-warning m-y-5" href="#download">Get The App</a>
          </div> <!-- .section-content -->
        </div>
      </div>
      <div class="col-sm-6 col-md-p-l-1 m-t-60-xs-max">
        <div class="col-inner clearfix">
          <img class="img-responsive float-r-sm-min m-x-auto-xs-max" src="assets/item/home.png" alt="" data-sr="right">
        </div>
      </div>
    </div>
  </div>
</div> <!-- #home -->

app/views/layouts/_footer.html.erb
<footer class="site-footer block-invert">
  <div class="container">
    <img class="site-footer-logo img-responsive" src="assets/site-footer-logo.png" data-sr="bottom">
    <ul class="site-footer-social-list">
      <li><a href="https://www.facebook.com/" target="_blank">Facebook</a></li>
      <li><a href="https://twitter.com/" target="_blank">Twitter</a></li>
      <li><a href="https://instagram.com/" target="_blank">Instagram</a></li>
      <li><a href="https://www.linkedin.com/" target="_blank">LinkedIn</a></li>
      <li><a href="https://www.pinterest.com/" target="_blank">Pinterest</a></li>
    </ul>
    <p class="site-footer-copyright">2016 © <a href="#" target="_blank">your copyright info</a> | all rights reserved.</p>
  </div>
</footer> <!-- .site-footer -->

app/views/layouts/_nav.html.erb
<header class="site-header">
  <nav class="navbar navbar-theme">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <div class="navbar-brand-wrap">
          <a class="navbar-brand" href="#">
            <img src="assets/site-header-logo.png" alt="">
          </a>
        </div>
      </div> <!-- .navbar-header -->

      <div class="collapse navbar-collapse" id="navbar-collapse">
        <ul class="nav navbar-nav navbar-right">
          <li class="active"><a href="#home">Home</a></li>
          <li><a href="#about">About</a></li>
          <li><a href="#brief_1">Brief</a></li>
          <li><a href="#pricing">Pricing</a></li>
          <li><a href="#download">Download</a></li>
          <li><a href="#contact">Contact</a></li>

          <% if user_signed_in? %>
            <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
          <% else %>
            <li><%= link_to 'Sign Up', new_user_registration_path %></li>
            <li><%= link_to 'Sign In', new_user_session_path %></li>
          <% end %>
          
        </ul>
      </div> <!-- .navbar-collapse -->
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Asscky</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/landing_page.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Asscky</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="site">
      <div class="site-loader">
        <div class="site-loader-spinner"></div>
      </div> <!-- .site-loader -->

      <div class="site-canvas">        
        <%= render 'layouts/nav' %>        

        <main class="site-main">
          <%= render 'landing_page/top' %>
          <%= render 'landing_page/about' %>
          <%= render 'landing_page/brief' %>
          <%= render 'landing_page/pricing' %>
          <%= render 'landing_page/download' %>
          <%= render 'landing_page/contact' %>
        </main> <!-- .site-main -->
        
        <%= render 'layouts/footer' %>
      </div>
    </div>

    <script src='assets/main.js'></script>
  </body>
</html>

app/views/messages/_message.html.erb
<div class="card">
  <div class="card-block">
    <div class="row">
      <div class="col-md-1">
        <%= message.user_id %>
      </div>
      <div class="col-md-11">
        <p class="card-text">
          <span class="text-muted"><%= message.user_id %> at <%= message.timestamp %> says</span><br>
          <%= message.body %>
        </p>
      </div>
    </div>
  </div>
</div>